// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDemo.Data;

namespace WebDemo.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20210607234929_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Arabic_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GenericContext.Database.Models.EventRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "IX_EventRecipient_EventId");

                    b.ToTable("EventRecipient", "notif");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TemplateId" }, "IX_Events_TemplateId");

                    b.ToTable("Events", "notif");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("NotificationBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Notifications_CreatorId");

                    b.HasIndex(new[] { "EventId" }, "IX_Notifications_EventId");

                    b.ToTable("Notifications", "notif");
                });

            modelBuilder.Entity("GenericContext.Database.Models.ReferenceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReferenceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceType", "notif");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Templates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates", "notif");
                });

            modelBuilder.Entity("GenericContext.Database.Models.UserNotifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeenDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NotificationId" }, "IX_UserNotifications_NotificationId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserNotifications_UserId");

                    b.ToTable("UserNotifications", "notif");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", "security", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("GenericContext.Database.Models.EventRecipient", b =>
                {
                    b.HasOne("GenericContext.Database.Models.Events", "Event")
                        .WithMany("EventRecipient")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_EventRecipient_Events")
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Events", b =>
                {
                    b.HasOne("GenericContext.Database.Models.Templates", "Template")
                        .WithMany("Events")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("FK_Events_Templates")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Notifications", b =>
                {
                    b.HasOne("GenericContext.Database.Models.Events", "Event")
                        .WithMany("Notifications")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_Notifications_Events")
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GenericContext.Database.Models.UserNotifications", b =>
                {
                    b.HasOne("GenericContext.Database.Models.Notifications", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .HasConstraintName("FK_UserNotifications_Notifications")
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Events", b =>
                {
                    b.Navigation("EventRecipient");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Notifications", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("GenericContext.Database.Models.Templates", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
